language: java

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      sudo: false
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8.3
      script: ./gradlew -u -S --no-daemon --no-parallel build

# The 'build' task runs most things, including test, check, & static analysis
install: true
script:
  - ./gradlew -u -S --no-daemon --no-parallel build check
