environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  os: Visual Studio 2017 # Windows Server 2016
install:
  - java -version
  - gradlew.bat --version
build: off
test_script:
  - gradlew.bat -u -S --no-daemon --no-parallel build
cache:
  - C:\Users\appveyor\.gradle
